// Generated by scripts/render_snippets.py. Do not edit.
import { readFileSync } from "node:fs";
import { parseJson, type Alignment } from "betula";

const alignment: Alignment = parseJson("Alignment", readFileSync("alignment.json", "utf8"));
// Alignment is a union type: WrappedAlignment | UnwrappedAlignment
console.log(alignment);
