// Generated by scripts/render_snippets.py. Do not edit.
import { readFileSync } from "node:fs";
import { parseJson, type Annotation } from "betula";

const annotation: Annotation = parseJson("Annotation", readFileSync("annotation.json", "utf8"));
console.log(annotation);
