// Generated by scripts/render_snippets.py. Do not edit.
import { readFileSync } from "node:fs";
import { parseJson, type DistanceMatrix } from "betula";

const distanceMatrix: DistanceMatrix = parseJson("DistanceMatrix", readFileSync("distance-matrix.json", "utf8"));
console.log(distanceMatrix);
