// Generated by scripts/render_snippets.py. Do not edit.
import { readFileSync } from "node:fs";
import { parseJson, type Sequence } from "betula";

const sequence: Sequence = parseJson("Sequence", readFileSync("sequence.json", "utf8"));
// Sequence is a union type: DnaSequence | RnaSequence | ProteinSequence | UntypedSequence
console.log(sequence);
