// Generated by scripts/render_snippets.py. Do not edit.
import { readFileSync } from "node:fs";
import { parseJson, type Tree } from "betula";

const tree: Tree = parseJson("Tree", readFileSync("tree.json", "utf8"));
console.log(tree);
