# generated by datamodel-codegen:
#   filename:  betula.bundle.schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Betula(RootModel[Any]):
    root: Any = Field(
        ...,
        description='All betula schemas bundled into one document for code generation. Generated by scripts/bundle_schema.py; do not edit.',
        title='Betula',
    )


class MatrixItem(RootModel[float]):
    root: float = Field(..., ge=0.0)


class DnaAlphabet(RootModel[str]):
    root: str = Field(
        ...,
        description="IUPAC nucleotide codes for DNA: A/C/G/T plus the standard ambiguity codes (R,Y,S,W,K,M,B,D,H,V,N). Also allows '-' and '.' as alignment gap/missing-data characters, since a Sequence doubles as an alignment row. Case-insensitive (lowercase is the common convention for soft-masked regions in genome assemblies).",
        min_length=1,
        pattern='^[ACGTRYSWKMBDHVNacgtryswkmbdhvn.-]*$',
        title='DnaAlphabet',
    )


class Hsp(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: int = Field(..., ge=1)
    bitScore: float
    score: float
    evalue: float = Field(..., ge=0.0)
    identity: int = Field(..., ge=0)
    alignLen: int = Field(..., ge=1)
    queryFrom: int = Field(..., ge=1)
    queryTo: int = Field(..., ge=1)
    hitFrom: int = Field(..., ge=1)
    hitTo: int = Field(..., ge=1)
    qseq: str
    hseq: str
    midline: str


class Identifier(RootModel[str]):
    root: str = Field(
        ...,
        description='A short, stable identifier/label string: a sequence identifier, a GFF3 feature ID, a BLAST accession, etc.',
        min_length=1,
        title='Identifier',
    )


class Location(BaseModel):
    """
    A 1-based inclusive interval on a named reference sequence (GFF3 convention). Not yet consumed by another betula schema: annotation keeps seqid/start/end/strand flat to match picea's and react-bio-viz's current wire shape rather than nesting them under this. This exists as the reusable primitive for when a genomic-interval-only shape is needed, e.g. a future schema for react-bio-viz's GenomeBrowser feature tracks.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    seqid: Identifier
    start: int = Field(..., ge=1)
    end: int = Field(..., ge=1)
    strand: Literal['+', '-', '.']


class Metadata(RootModel[dict[str, str | list[str]]]):
    """
    Free-form key/value metadata, GFF3-attribute-style: each value is a single string, or a list of strings for multi-valued tags.
    """

    root: dict[str, str | list[str]]


class ProteinAlphabet(RootModel[str]):
    root: str = Field(
        ...,
        description="IUPAC amino acid codes: the standard 20 (A,C,D,E,F,G,H,I,K,L,M,N,P,Q,R,S,T,V,W,Y) plus the ambiguity/special codes B (Asx), Z (Glx), X (any), J (Leu/Ile), U (selenocysteine), O (pyrrolysine) -- together these cover all 26 letters, so this pattern is effectively any letter. Also allows '*' for a stop codon, and '-'/'.' as alignment gap/missing-data characters, since a Sequence doubles as an alignment row. Case-insensitive.",
        min_length=1,
        pattern='^[A-Za-z*.-]*$',
        title='ProteinAlphabet',
    )


class ProteinSequence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['protein-sequence']
    identifier: Identifier
    sequence: ProteinAlphabet


class RnaAlphabet(RootModel[str]):
    root: str = Field(
        ...,
        description="IUPAC nucleotide codes for RNA: A/C/G/U plus the standard ambiguity codes (R,Y,S,W,K,M,B,D,H,V,N). 'T' is deliberately excluded (that's DnaAlphabet). Also allows '-' and '.' as alignment gap/missing-data characters, since a Sequence doubles as an alignment row. Case-insensitive.",
        min_length=1,
        pattern='^[ACGURYSWKMBDHVNacguryswkmbdhvn.-]*$',
        title='RnaAlphabet',
    )


class RnaSequence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['rna-sequence']
    identifier: Identifier
    sequence: RnaAlphabet


class SequenceReference(BaseModel):
    """
    A pointer to a Sequence by identifier, without embedding the sequence itself. Not yet consumed by another betula schema (every current producer embeds full Sequence objects, e.g. in alignment); this exists as the reusable primitive for when a by-reference link is needed, e.g. a hit record pointing at a locally-known query sequence instead of repeating it.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    identifier: Identifier


class TaxonomyNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    name: str
    ancestors: list[int]
    children: list[TaxonomyNode] | None = None
    depth: int | None = Field(None, ge=0)
    count: int | None = Field(None, ge=0)


class Tree(BaseModel):
    """
    A phylogenetic (or other hierarchical) tree node, shared by picea, react-bio-viz, acacia, and iqtreeserver. The root of a tree is itself a Tree node; a whole tree and a single node use the same shape, so 'type' is optional and conventionally set only on a node transmitted as a standalone document (typically the root), not repeated on every nested child.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['tree'] | None = Field(
        None,
        description="Wire-format object-kind discriminator (see betula's versioning policy). Optional; omit on nested children.",
    )
    id: str | int | None = Field(
        None,
        description='Optional node identifier. Not every producer assigns one at parse time (acacia/iqtreeserver derive ids separately); consumers must not assume it is present.',
    )
    name: str = Field(
        ...,
        description='Raw node label: a leaf name, or an internal-node label such as a bootstrap value or support string (e.g. picea\'s "0.989", IQ-TREE\'s "95.3/88"). Kept as the original string for round-tripping; parse further only if you know the producer\'s convention.',
    )
    length: float = Field(
        ..., description='Branch length leading to this node.', ge=0.0
    )
    children: list[Tree] = Field(
        ..., description='Child nodes. Empty array for a leaf.'
    )


class UntypedSequence(BaseModel):
    """
    The shape every current producer (picea, react-bio-viz, acacia) actually emits: no alphabet discriminator.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    identifier: Identifier
    sequence: str = Field(..., min_length=1)


class Annotation(BaseModel):
    """
    A GFF3-derived sequence feature (gene model) node. Shared verbatim between picea (SequenceInterval) and react-bio-viz (SequenceInterval). seqid/start/end/strand stay flat rather than nesting under core/Location, to match the real current wire shape exactly.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['annotation'] | None = Field(
        None,
        description="Wire-format object-kind discriminator (see betula's versioning policy). Optional. Distinct from 'interval_type': 'type' says this is a betula Annotation object, 'interval_type' says which GFF3 feature kind it is.",
    )
    ID: Identifier
    seqid: Identifier = Field(
        ..., description='GFF3 column 1: the reference sequence this feature is on.'
    )
    source: str = Field(..., description='GFF3 column 2.')
    interval_type: str = Field(
        ...,
        description="GFF3 column 3 (feature type), e.g. 'gene', 'mRNA', 'exon', 'CDS'.",
        min_length=1,
    )
    start: int = Field(..., description='GFF3 column 4: 1-based inclusive start.', ge=1)
    end: int = Field(..., description='GFF3 column 5: 1-based inclusive end.', ge=1)
    score: float | Literal['.'] = Field(
        ..., description="GFF3 column 6. '.' is the GFF3 convention for 'no score'."
    )
    strand: Literal['+', '-', '.'] = Field(..., description='GFF3 column 7.')
    phase: Literal[0, 1, 2] | Literal['.'] = Field(
        ...,
        description="GFF3 column 8 (CDS reading-frame phase). '.' is the GFF3 convention for 'not applicable'.",
    )
    attributes: Metadata
    children: list[Annotation] = Field(
        ..., description='Nested features, e.g. mRNA under gene, exon/CDS under mRNA.'
    )


class DistanceMatrix(BaseModel):
    """
    A pairwise distance matrix, shared by react-bio-viz and acacia (via @holmrenser/nj's DistanceResult). Squareness, symmetry, and a zero diagonal are semantic constraints, not checked structurally by this schema.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['distance-matrix'] | None = Field(
        None,
        description="Wire-format object-kind discriminator (see betula's versioning policy). Optional.",
    )
    labels: list[Identifier] = Field(..., min_length=1)
    matrix: list[list[MatrixItem]]
    labelNames: dict[str, str] | None = Field(
        None,
        description='Optional display-name lookup from label to a longer/human-readable name.',
    )


class DnaSequence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['dna-sequence']
    identifier: Identifier
    sequence: DnaAlphabet


class HitMember(BaseModel):
    """
    One member of a clustered hit (e.g. in a clustered_nr database); a non-clustered hit has exactly one member.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    accession: Identifier
    title: str
    taxid: int
    name: str


class Sequence(
    RootModel[DnaSequence | RnaSequence | ProteinSequence | UntypedSequence]
):
    root: DnaSequence | RnaSequence | ProteinSequence | UntypedSequence = Field(
        ...,
        description="A single biological sequence record, shared by picea, react-bio-viz, and acacia (FASTA-derived). 'type' is an optional alphabet discriminator: every current producer omits it and emits the plain UntypedSequence shape, which remains valid. Set it when the alphabet is known so consumers get both a proper discriminated union and IUPAC alphabet validation on 'sequence' (core/dna-alphabet, core/rna-alphabet, core/protein-alphabet) instead of an unconstrained string.",
        title='Sequence',
    )


class UnwrappedAlignment(RootModel[list[Sequence]]):
    """
    The shape every current producer (react-bio-viz, acacia) actually emits: no wrapper, no discriminator.
    """

    root: list[Sequence] = Field(
        ...,
        description='The shape every current producer (react-bio-viz, acacia) actually emits: no wrapper, no discriminator.',
        min_length=1,
    )


class WrappedAlignment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['alignment'] = Field(
        ...,
        description="Wire-format object-kind discriminator (see betula's versioning policy).",
    )
    sequences: list[Sequence] = Field(..., min_length=1)


class Alignment(RootModel[WrappedAlignment | UnwrappedAlignment]):
    root: WrappedAlignment | UnwrappedAlignment = Field(
        ...,
        description="A multiple sequence alignment: a list of Sequence records. Conventionally all sequences have the same length once gaps are included, but that is a semantic constraint, not checked structurally by this schema. Accepts either the bare-array shape every current producer (react-bio-viz's AlignedSequences, acacia's MSAData) actually emits, or a wrapped object carrying the wire-format 'type' discriminator for producers that want one.",
        title='Alignment',
    )


class Hit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accession: Identifier
    title: str
    taxid: int
    saccver: Identifier
    name: str = Field(..., description='Resolved taxon scientific name.')
    members: list[HitMember] = Field(..., min_length=1)
    clusterSize: int = Field(..., ge=1)
    queryCover: float = Field(..., ge=0.0, le=100.0)
    percentIdentity: float = Field(..., ge=0.0, le=100.0)
    num: int
    len: int = Field(..., ge=1)
    hsps: list[Hsp] = Field(..., min_length=1)
    ancestors: list[int] = Field(..., description='Taxonomy lineage taxids.')


class BlastResult(BaseModel):
    """
    A full BLAST search result, matching blastserver's parsed-XML shape: hit-level, with nested HSPs and taxonomy/cluster enrichment. react-bio-viz's flattened single-row-per-hit visualization shape is a derived view of this, not a separate wire format. Numeric fields here are typed as numbers; blastserver's raw XML parse currently yields numeric strings and must cast before serializing against this schema.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['blast-result'] | None = Field(
        None,
        description="Wire-format object-kind discriminator (see betula's versioning policy). Optional.",
    )
    program: str
    version: str
    db: str
    queryId: Identifier
    queryLen: int = Field(..., ge=1)
    queryTitle: str
    hits: list[Hit]
    stat: str
    message: str
    taxonomyTrees: list[TaxonomyNode] | None = None


TaxonomyNode.model_rebuild()
Tree.model_rebuild()
Annotation.model_rebuild()
