// Generated by scripts/render_snippets.py. Do not edit.
//! Runs every examples/schemas/*.rs snippet against its schema's first valid fixture.

mod alignment {
    include!("../examples/schemas/alignment.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod annotation {
    include!("../examples/schemas/annotation.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod blast_result {
    include!("../examples/schemas/blast-result.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod dna_alphabet {
    include!("../examples/schemas/core/dna-alphabet.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod identifier {
    include!("../examples/schemas/core/identifier.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod location {
    include!("../examples/schemas/core/location.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod metadata {
    include!("../examples/schemas/core/metadata.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod protein_alphabet {
    include!("../examples/schemas/core/protein-alphabet.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod rna_alphabet {
    include!("../examples/schemas/core/rna-alphabet.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod sequence_reference {
    include!("../examples/schemas/core/sequence-reference.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod distance_matrix {
    include!("../examples/schemas/distance-matrix.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod sequence {
    include!("../examples/schemas/sequence.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod tree {
    include!("../examples/schemas/tree.rs");
    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

#[test]
fn schema_snippets() {
    let dir = std::env::temp_dir().join(format!("betula-snippets-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let examples = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../examples");
    let fixtures = [
        ("alignment.json", "alignment/valid/simple.json"),
        ("annotation.json", "annotation/valid/gene-with-mrna.json"),
        ("blast-result.json", "blast-result/valid/simple.json"),
        ("dna-alphabet.json", "core/dna-alphabet/valid/ambiguity-codes.json"),
        ("identifier.json", "core/identifier/valid/simple.json"),
        ("location.json", "core/location/valid/simple.json"),
        ("metadata.json", "core/metadata/valid/simple.json"),
        ("protein-alphabet.json", "core/protein-alphabet/valid/ambiguity-and-stop.json"),
        ("rna-alphabet.json", "core/rna-alphabet/valid/ambiguity-codes.json"),
        ("sequence-reference.json", "core/sequence-reference/valid/simple.json"),
        ("distance-matrix.json", "distance-matrix/valid/simple.json"),
        ("sequence.json", "sequence/valid/dna-with-ambiguity-and-gaps.json"),
        ("tree.json", "tree/valid/with-id-and-support.json"),
    ];
    for (file, fixture) in fixtures {
        std::fs::copy(examples.join(fixture), dir.join(file)).unwrap();
    }
    std::env::set_current_dir(&dir).unwrap();
    let snippets: [(&str, fn() -> Result<(), Box<dyn std::error::Error>>); 13] = [
        ("alignment", alignment::run),
        ("annotation", annotation::run),
        ("blast_result", blast_result::run),
        ("dna_alphabet", dna_alphabet::run),
        ("identifier", identifier::run),
        ("location", location::run),
        ("metadata", metadata::run),
        ("protein_alphabet", protein_alphabet::run),
        ("rna_alphabet", rna_alphabet::run),
        ("sequence_reference", sequence_reference::run),
        ("distance_matrix", distance_matrix::run),
        ("sequence", sequence::run),
        ("tree", tree::run),
    ];
    for (name, run) in snippets {
        run().unwrap_or_else(|err| panic!("{name} snippet failed: {err}"));
    }
}
