# Generated by scripts/render_snippets.py. Do not edit.
import betula

with open("alignment.json") as f:
    alignment = betula.parse_json(betula.Alignment, f.read())
# alignment.root is the matched variant: WrappedAlignment, or UnwrappedAlignment
print(alignment)
