# Generated by scripts/render_snippets.py. Do not edit.
from betula_schema import Alignment, parse_json

with open("alignment.json") as f:
    alignment = parse_json(Alignment, f.read())
# alignment.root is the matched variant: WrappedAlignment, or UnwrappedAlignment
print(alignment)
