# Generated by scripts/render_snippets.py. Do not edit.
from betula_schema import Annotation, parse_json

with open("annotation.json") as f:
    annotation = parse_json(Annotation, f.read())
print(annotation)
