# Generated by scripts/render_snippets.py. Do not edit.
from betula_schema import DistanceMatrix, parse_json

with open("distance-matrix.json") as f:
    distance_matrix = parse_json(DistanceMatrix, f.read())
print(distance_matrix)
