# Generated by scripts/render_snippets.py. Do not edit.
import betula

with open("distance-matrix.json") as f:
    distance_matrix = betula.parse_json(betula.DistanceMatrix, f.read())
print(distance_matrix)
