# Generated by scripts/render_snippets.py. Do not edit.
from betula_schema import Sequence, parse_json

with open("sequence.json") as f:
    sequence = parse_json(Sequence, f.read())
# sequence.root is the matched variant: DnaSequence, RnaSequence, ProteinSequence, or UntypedSequence
print(sequence)
