# Generated by scripts/render_snippets.py. Do not edit.
import betula

with open("sequence.json") as f:
    sequence = betula.parse_json(betula.Sequence, f.read())
# sequence.root is the matched variant: DnaSequence, RnaSequence, ProteinSequence, or UntypedSequence
print(sequence)
