// Generated by scripts/render_snippets.py. Do not edit.
import { readFileSync } from "node:fs";
import { parseJson, type DnaAlphabet } from "betula";

const dnaAlphabet: DnaAlphabet = parseJson("DnaAlphabet", readFileSync("dna-alphabet.json", "utf8"));
console.log(dnaAlphabet);
