// Generated by scripts/render_snippets.py. Do not edit.
import { readFileSync } from "node:fs";
import { parseJson, type Identifier } from "betula-schema";

const identifier: Identifier = parseJson("Identifier", readFileSync("identifier.json", "utf8"));
console.log(identifier);
