// Generated by scripts/render_snippets.py. Do not edit.
import { readFileSync } from "node:fs";
import { parseJson, type Location } from "betula";

const location: Location = parseJson("Location", readFileSync("location.json", "utf8"));
console.log(location);
