// Generated by scripts/render_snippets.py. Do not edit.
import { readFileSync } from "node:fs";
import { parseJson, type Metadata } from "betula";

const metadata: Metadata = parseJson("Metadata", readFileSync("metadata.json", "utf8"));
console.log(metadata);
