// Generated by scripts/render_snippets.py. Do not edit.
import { readFileSync } from "node:fs";
import { parseJson, type ProteinAlphabet } from "betula-schema";

const proteinAlphabet: ProteinAlphabet = parseJson("ProteinAlphabet", readFileSync("protein-alphabet.json", "utf8"));
console.log(proteinAlphabet);
