// Generated by scripts/render_snippets.py. Do not edit.
import { readFileSync } from "node:fs";
import { parseJson, type RnaAlphabet } from "betula-schema";

const rnaAlphabet: RnaAlphabet = parseJson("RnaAlphabet", readFileSync("rna-alphabet.json", "utf8"));
console.log(rnaAlphabet);
