// Generated by scripts/render_snippets.py. Do not edit.
import { readFileSync } from "node:fs";
import { parseJson, type SequenceReference } from "betula";

const sequenceReference: SequenceReference = parseJson("SequenceReference", readFileSync("sequence-reference.json", "utf8"));
console.log(sequenceReference);
