# Generated by scripts/render_snippets.py. Do not edit.
import betula

with open("dna-alphabet.json") as f:
    dna_alphabet = betula.parse_json(betula.DnaAlphabet, f.read())
# DnaAlphabet is a RootModel; dna_alphabet.root is the plain value
print(dna_alphabet)
