# Generated by scripts/render_snippets.py. Do not edit.
from betula_schema import DnaAlphabet, parse_json

with open("dna-alphabet.json") as f:
    dna_alphabet = parse_json(DnaAlphabet, f.read())
# DnaAlphabet is a RootModel; dna_alphabet.root is the plain value
print(dna_alphabet)
