# Generated by scripts/render_snippets.py. Do not edit.
import betula

with open("identifier.json") as f:
    identifier = betula.parse_json(betula.Identifier, f.read())
# Identifier is a RootModel; identifier.root is the plain value
print(identifier)
