# Generated by scripts/render_snippets.py. Do not edit.
from betula_schema import Identifier, parse_json

with open("identifier.json") as f:
    identifier = parse_json(Identifier, f.read())
# Identifier is a RootModel; identifier.root is the plain value
print(identifier)
