# Generated by scripts/render_snippets.py. Do not edit.
from betula_schema import Metadata, parse_json

with open("metadata.json") as f:
    metadata = parse_json(Metadata, f.read())
# Metadata is a RootModel; metadata.root is the plain value
print(metadata)
