# Generated by scripts/render_snippets.py. Do not edit.
import betula

with open("metadata.json") as f:
    metadata = betula.parse_json(betula.Metadata, f.read())
# Metadata is a RootModel; metadata.root is the plain value
print(metadata)
