# Generated by scripts/render_snippets.py. Do not edit.
import betula

with open("protein-alphabet.json") as f:
    protein_alphabet = betula.parse_json(betula.ProteinAlphabet, f.read())
# ProteinAlphabet is a RootModel; protein_alphabet.root is the plain value
print(protein_alphabet)
