# Generated by scripts/render_snippets.py. Do not edit.
from betula_schema import ProteinAlphabet, parse_json

with open("protein-alphabet.json") as f:
    protein_alphabet = parse_json(ProteinAlphabet, f.read())
# ProteinAlphabet is a RootModel; protein_alphabet.root is the plain value
print(protein_alphabet)
