# Generated by scripts/render_snippets.py. Do not edit.
from betula_schema import RnaAlphabet, parse_json

with open("rna-alphabet.json") as f:
    rna_alphabet = parse_json(RnaAlphabet, f.read())
# RnaAlphabet is a RootModel; rna_alphabet.root is the plain value
print(rna_alphabet)
