# Generated by scripts/render_snippets.py. Do not edit.
import betula

with open("rna-alphabet.json") as f:
    rna_alphabet = betula.parse_json(betula.RnaAlphabet, f.read())
# RnaAlphabet is a RootModel; rna_alphabet.root is the plain value
print(rna_alphabet)
