# Generated by scripts/render_snippets.py. Do not edit.
import betula

with open("sequence-reference.json") as f:
    sequence_reference = betula.parse_json(betula.SequenceReference, f.read())
print(sequence_reference)
