# Generated by scripts/render_snippets.py. Do not edit.
from betula_schema import SequenceReference, parse_json

with open("sequence-reference.json") as f:
    sequence_reference = parse_json(SequenceReference, f.read())
print(sequence_reference)
