#!/usr/bin/env node
// Generate src/types.ts and src/schema.ts from the bundled betula schema
// (build/betula.bundle.schema.json, produced by scripts/bundle_schema.py).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const pkgDir = join(fileURLToPath(import.meta.url), "..", "..");
const bundlePath = process.argv[2] ?? join(pkgDir, "..", "..", "build", "betula.bundle.schema.json");
const bundle = JSON.parse(readFileSync(bundlePath, "utf8"));
const banner = "// Generated by bindings/typescript/scripts/generate.mjs from the betula schemas. Do not edit.\n";

// The bundle root only exists to hold $defs and has no meaningful type of its
// own, so remove the catch-all interface the generator emits for it.
const { description: _description, ...root } = bundle;
let types = await compile(root, "Betula", {
  unreachableDefinitions: true,
  additionalProperties: false,
  bannerComment: "",
  format: false,
});
const rootBlock = "export interface Betula {\n[k: string]: unknown\n}\n";
if (types.split(rootBlock).length !== 2) {
  throw new Error("expected exactly one root `Betula` interface in generated output; json-schema-to-typescript output changed");
}
types = types.replace(rootBlock, "");

const kinds = Object.keys(bundle.$defs);
const typeMap = [
  "/** Every betula schema title, mapped to its TypeScript type. */",
  "export interface BetulaTypes {",
  ...kinds.map((k) => `  ${k}: ${k};`),
  "}",
  "",
].join("\n");

writeFileSync(join(pkgDir, "src", "types.ts"), `${banner}\n${types}\n${typeMap}`);
writeFileSync(
  join(pkgDir, "src", "schema.ts"),
  `${banner}\nexport const schema = ${JSON.stringify(bundle, null, 2)} as const;\n`,
);
console.log(`Wrote ${kinds.length} types to src/types.ts and src/schema.ts`);
