// Generated by scripts/render_snippets.py. Do not edit.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string("dna-alphabet.json")?;
    let dna_alphabet: betula::DnaAlphabet = betula::parse_str(&text)?;
    // DnaAlphabet is a newtype; deref it (&*dna_alphabet) for the inner value
    println!("{dna_alphabet:?}");
    Ok(())
}
