// Generated by scripts/render_snippets.py. Do not edit.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string("identifier.json")?;
    let identifier: betula::Identifier = betula::parse_str(&text)?;
    // Identifier is a newtype; deref it (&*identifier) for the inner value
    println!("{identifier:?}");
    Ok(())
}
