// Generated by scripts/render_snippets.py. Do not edit.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string("location.json")?;
    let location: betula_schema::Location = betula_schema::parse_str(&text)?;
    println!("{location:?}");
    Ok(())
}
