// Generated by scripts/render_snippets.py. Do not edit.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string("metadata.json")?;
    let metadata: betula::Metadata = betula::parse_str(&text)?;
    // Metadata is a newtype; deref it (&*metadata) for the inner value
    println!("{metadata:?}");
    Ok(())
}
