// Generated by scripts/render_snippets.py. Do not edit.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string("protein-alphabet.json")?;
    let protein_alphabet: betula_schema::ProteinAlphabet = betula_schema::parse_str(&text)?;
    // ProteinAlphabet is a newtype; deref it (&*protein_alphabet) for the inner value
    println!("{protein_alphabet:?}");
    Ok(())
}
