// Generated by scripts/render_snippets.py. Do not edit.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string("rna-alphabet.json")?;
    let rna_alphabet: betula::RnaAlphabet = betula::parse_str(&text)?;
    // RnaAlphabet is a newtype; deref it (&*rna_alphabet) for the inner value
    println!("{rna_alphabet:?}");
    Ok(())
}
