// Generated by scripts/render_snippets.py. Do not edit.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string("sequence-reference.json")?;
    let sequence_reference: betula::SequenceReference = betula::parse_str(&text)?;
    println!("{sequence_reference:?}");
    Ok(())
}
