// Generated by scripts/render_snippets.py. Do not edit.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string("alignment.json")?;
    let alignment: betula::Alignment = betula::parse_str(&text)?;
    // Alignment is an enum with one variant per alternative, e.g. Alignment::WrappedAlignment(_)
    println!("{alignment:?}");
    Ok(())
}
