// Generated by scripts/render_snippets.py. Do not edit.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string("annotation.json")?;
    let annotation: betula_schema::Annotation = betula_schema::parse_str(&text)?;
    println!("{annotation:?}");
    Ok(())
}
