// Generated by scripts/render_snippets.py. Do not edit.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string("distance-matrix.json")?;
    let distance_matrix: betula_schema::DistanceMatrix = betula_schema::parse_str(&text)?;
    println!("{distance_matrix:?}");
    Ok(())
}
