// Generated by scripts/render_snippets.py. Do not edit.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string("sequence.json")?;
    let sequence: betula_schema::Sequence = betula_schema::parse_str(&text)?;
    // Sequence is an enum with one variant per alternative, e.g. Sequence::DnaSequence(_)
    println!("{sequence:?}");
    Ok(())
}
