// Generated by scripts/render_snippets.py. Do not edit.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string("tree.json")?;
    let tree: betula_schema::Tree = betula_schema::parse_str(&text)?;
    println!("{tree:?}");
    Ok(())
}
