#!/usr/bin/env python3
"""Bundle schema/**/*.schema.json into one self-contained schema for codegen.

The source schemas $ref each other by absolute $id
(https://schemas.wur.nl/...), which code generators try to fetch over the
network. This inlines every schema under a single top-level $defs, keyed by
its title, hoists each schema's own $defs alongside, and rewrites every
$ref to a local "#/$defs/<Name>" pointer.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_DIR = ROOT / "schema"
DEFAULT_OUT = ROOT / "build" / "betula.bundle.schema.json"


def load_schemas() -> dict[str, dict]:
    return {
        path.relative_to(SCHEMA_DIR).as_posix().removesuffix(".schema.json"): json.loads(path.read_text())
        for path in sorted(SCHEMA_DIR.rglob("*.schema.json"))
    }


def rewrite_refs(node, own_title: str, id_to_title: dict[str, str]):
    if isinstance(node, list):
        return [rewrite_refs(item, own_title, id_to_title) for item in node]
    if not isinstance(node, dict):
        return node
    out = {}
    for key, value in node.items():
        if key == "$ref":
            out[key] = local_ref(value, own_title, id_to_title)
        elif key in ("$id", "$schema", "$defs"):
            continue
        else:
            out[key] = rewrite_refs(value, own_title, id_to_title)
    return out


def local_ref(ref: str, own_title: str, id_to_title: dict[str, str]) -> str:
    if ref == "#":
        return f"#/$defs/{own_title}"
    if ref.startswith("#/$defs/"):
        return ref
    base, _, fragment = ref.partition("#")
    if base not in id_to_title:
        raise ValueError(f"unresolvable $ref {ref!r} in {own_title}")
    if fragment.startswith("/$defs/"):
        return f"#{fragment}"
    return f"#/$defs/{id_to_title[base]}"


def bundle(schemas: dict[str, dict]) -> dict:
    id_to_title = {schema["$id"]: schema["title"] for schema in schemas.values()}
    defs: dict[str, dict] = {}

    def add(name: str, definition: dict, origin: str) -> None:
        if name in defs:
            raise ValueError(f"duplicate definition name {name!r} (from {origin})")
        defs[name] = definition

    for name, schema in schemas.items():
        title = schema["title"]
        add(title, rewrite_refs(schema, title, id_to_title), name)
        for def_name, def_schema in schema.get("$defs", {}).items():
            add(def_name, rewrite_refs(def_schema, title, id_to_title), f"{name}#/$defs/{def_name}")

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://schemas.wur.nl/betula/bundle/schema.json",
        "title": "Betula",
        "description": "All betula schemas bundled into one document for code generation. Generated by scripts/bundle_schema.py; do not edit.",
        "$defs": dict(sorted(defs.items())),
    }


def main() -> None:
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUT
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(bundle(load_schemas()), indent=2) + "\n")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
