#!/usr/bin/env python3
"""Write a short "parse this schema" snippet per schema for each binding.

Outputs (all generated; scripts/generate_bindings.sh runs this, and CI fails
if the committed files are stale):

  bindings/python/examples/schemas/<name>.py
  bindings/typescript/examples/schemas/<name>.ts
  bindings/rust/examples/schemas/<name>.rs
  bindings/rust/tests/snippets.rs   (runs every Rust snippet)

Each snippet reads `<file>.json` from the working directory, parses it as the
schema's type, and prints the result. Every binding's test suite runs every
snippet against that schema's first valid fixture, and the docs include the
same files on each schema page, so the docs only show code CI runs.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_DIR = ROOT / "schema"
EXAMPLES_DIR = ROOT / "examples"
BINDINGS = ROOT / "bindings"
HEADER = "Generated by scripts/render_snippets.py. Do not edit."


def load_schemas() -> dict[str, dict]:
    return {
        path.relative_to(SCHEMA_DIR).as_posix().removesuffix(".schema.json"): json.loads(path.read_text())
        for path in sorted(SCHEMA_DIR.rglob("*.schema.json"))
    }


def snake(title: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", title).lower()


def camel(title: str) -> str:
    return title[0].lower() + title[1:]


def kebab(title: str) -> str:
    return snake(title).replace("_", "-")


def shape(schema: dict) -> str:
    """'union' (oneOf), 'struct' (object with properties), or 'wrapper' (anything else)."""
    if "oneOf" in schema:
        return "union"
    if schema.get("type") == "object" and "properties" in schema:
        return "struct"
    return "wrapper"


def variants(schema: dict) -> list[str]:
    return [sub["$ref"].rsplit("/", 1)[-1] for sub in schema.get("oneOf", [])]


def python_snippet(title: str, schema: dict) -> str:
    var, file = snake(title), f"{kebab(title)}.json"
    lines = [f"# {HEADER}", "import betula", "", f'with open("{file}") as f:',
             f"    {var} = betula.parse_json(betula.{title}, f.read())"]
    if shape(schema) == "union":
        names = variants(schema)
        lines.append(f"# {var}.root is the matched variant: {', '.join(names[:-1])}, or {names[-1]}")
    elif shape(schema) == "wrapper":
        lines.append(f"# {title} is a RootModel; {var}.root is the plain value")
    return "\n".join(lines + [f"print({var})", ""])


def typescript_snippet(title: str, schema: dict) -> str:
    var, file = camel(title), f"{kebab(title)}.json"
    lines = [f"// {HEADER}", 'import { readFileSync } from "node:fs";',
             f'import {{ parseJson, type {title} }} from "betula";', "",
             f'const {var}: {title} = parseJson("{title}", readFileSync("{file}", "utf8"));']
    if shape(schema) == "union":
        lines.append(f"// {title} is a union type: {' | '.join(variants(schema))}")
    return "\n".join(lines + [f"console.log({var});", ""])


def rust_snippet(title: str, schema: dict) -> str:
    var, file = snake(title), f"{kebab(title)}.json"
    lines = [f"// {HEADER}", "fn main() -> Result<(), Box<dyn std::error::Error>> {",
             f'    let text = std::fs::read_to_string("{file}")?;',
             f"    let {var}: betula::{title} = betula::parse_str(&text)?;"]
    if shape(schema) == "union":
        lines.append(f"    // {title} is an enum with one variant per alternative, e.g. {title}::{variants(schema)[0]}(_)")
    elif shape(schema) == "wrapper":
        lines.append(f"    // {title} is a newtype; deref it (&*{var}) for the inner value")
    return "\n".join(lines + [f'    println!("{{{var}:?}}");', "    Ok(())", "}", ""])


def rust_runner(entries: list[tuple[str, str, str]]) -> str:
    """entries: (module, snippet path from tests/, (file, fixture path from repo examples/))."""
    lines = [f"// {HEADER}", "//! Runs every examples/schemas/*.rs snippet against its schema's first valid fixture.", ""]
    for module, include, _, _ in entries:
        lines += [
            f"mod {module} {{",
            f'    include!("{include}");',
            "    pub(super) fn run() -> Result<(), Box<dyn std::error::Error>> {",
            "        main()",
            "    }",
            "}",
            "",
        ]
    lines += [
        "#[test]",
        "fn schema_snippets() {",
        '    let dir = std::env::temp_dir().join(format!("betula-snippets-{}", std::process::id()));',
        "    std::fs::create_dir_all(&dir).unwrap();",
        '    let examples = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../examples");',
        "    let fixtures = [",
        *[f'        ("{file}", "{fixture}"),' for _, _, file, fixture in entries],
        "    ];",
        "    for (file, fixture) in fixtures {",
        "        std::fs::copy(examples.join(fixture), dir.join(file)).unwrap();",
        "    }",
        "    std::env::set_current_dir(&dir).unwrap();",
        "    let snippets: [(&str, fn() -> Result<(), Box<dyn std::error::Error>>); " + str(len(entries)) + "] = [",
        *[f'        ("{module}", {module}::run),' for module, _, _, _ in entries],
        "    ];",
        "    for (name, run) in snippets {",
        '        run().unwrap_or_else(|err| panic!("{name} snippet failed: {err}"));',
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def first_valid_fixture(name: str) -> Path:
    fixtures = sorted((EXAMPLES_DIR / name / "valid").glob("*.json"))
    if not fixtures:
        raise SystemExit(f"schema {name} has no valid fixture to run its snippets against")
    return fixtures[0]


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def main() -> None:
    schemas = load_schemas()
    for lang in ("python/examples/schemas", "typescript/examples/schemas", "rust/examples/schemas"):
        for stale in (BINDINGS / lang).rglob("*.*") if (BINDINGS / lang).exists() else []:
            stale.unlink()

    rust_entries = []
    for name, schema in schemas.items():
        title = schema["title"]
        write(BINDINGS / "python/examples/schemas" / f"{name}.py", python_snippet(title, schema))
        write(BINDINGS / "typescript/examples/schemas" / f"{name}.ts", typescript_snippet(title, schema))
        write(BINDINGS / "rust/examples/schemas" / f"{name}.rs", rust_snippet(title, schema))
        fixture = first_valid_fixture(name).relative_to(EXAMPLES_DIR).as_posix()
        rust_entries.append((snake(title), f"../examples/schemas/{name}.rs", f"{kebab(title)}.json", fixture))

    write(BINDINGS / "rust/tests/snippets.rs", rust_runner(rust_entries))
    print(f"Wrote snippets for {len(schemas)} schemas")


if __name__ == "__main__":
    main()
