// Generated by bindings/typescript/scripts/generate.mjs from the betula schemas. Do not edit.

/**
 * A multiple sequence alignment: a list of Sequence records. Conventionally all sequences have the same length once gaps are included, but that is a semantic constraint, not checked structurally by this schema. Accepts either the bare-array shape every current producer (react-bio-viz's AlignedSequences, acacia's MSAData) actually emits, or a wrapped object carrying the wire-format 'type' discriminator for producers that want one.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "Alignment".
 */
export type Alignment = (WrappedAlignment | UnwrappedAlignment)
/**
 * A single biological sequence record, shared by picea, react-bio-viz, and acacia (FASTA-derived). 'type' is an optional alphabet discriminator: every current producer omits it and emits the plain UntypedSequence shape, which remains valid. Set it when the alphabet is known so consumers get both a proper discriminated union and IUPAC alphabet validation on 'sequence' (core/dna-alphabet, core/rna-alphabet, core/protein-alphabet) instead of an unconstrained string.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "Sequence".
 */
export type Sequence = (DnaSequence | RnaSequence | ProteinSequence | UntypedSequence)
/**
 * A short, stable identifier/label string: a sequence identifier, a GFF3 feature ID, a BLAST accession, etc.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "Identifier".
 */
export type Identifier = string
/**
 * IUPAC nucleotide codes for DNA: A/C/G/T plus the standard ambiguity codes (R,Y,S,W,K,M,B,D,H,V,N). Also allows '-' and '.' as alignment gap/missing-data characters, since a Sequence doubles as an alignment row. Case-insensitive (lowercase is the common convention for soft-masked regions in genome assemblies).
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "DnaAlphabet".
 */
export type DnaAlphabet = string
/**
 * IUPAC nucleotide codes for RNA: A/C/G/U plus the standard ambiguity codes (R,Y,S,W,K,M,B,D,H,V,N). 'T' is deliberately excluded (that's DnaAlphabet). Also allows '-' and '.' as alignment gap/missing-data characters, since a Sequence doubles as an alignment row. Case-insensitive.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "RnaAlphabet".
 */
export type RnaAlphabet = string
/**
 * IUPAC amino acid codes: the standard 20 (A,C,D,E,F,G,H,I,K,L,M,N,P,Q,R,S,T,V,W,Y) plus the ambiguity/special codes B (Asx), Z (Glx), X (any), J (Leu/Ile), U (selenocysteine), O (pyrrolysine) -- together these cover all 26 letters, so this pattern is effectively any letter. Also allows '*' for a stop codon, and '-'/'.' as alignment gap/missing-data characters, since a Sequence doubles as an alignment row. Case-insensitive.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "ProteinAlphabet".
 */
export type ProteinAlphabet = string
/**
 * The shape every current producer (react-bio-viz, acacia) actually emits: no wrapper, no discriminator.
 * 
 * @minItems 1
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "UnwrappedAlignment".
 */
export type UnwrappedAlignment = [Sequence, ...(Sequence)[]]
/**
 * A short, stable identifier/label string: a sequence identifier, a GFF3 feature ID, a BLAST accession, etc.
 */
export type Identifier1 = string

/**
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "WrappedAlignment".
 */
export interface WrappedAlignment {
/**
 * Wire-format object-kind discriminator (see betula's versioning policy).
 */
type: "alignment"
/**
 * @minItems 1
 */
sequences: [Sequence, ...(Sequence)[]]
}
/**
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "DnaSequence".
 */
export interface DnaSequence {
type: "dna-sequence"
identifier: Identifier
sequence: DnaAlphabet
}
/**
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "RnaSequence".
 */
export interface RnaSequence {
type: "rna-sequence"
identifier: Identifier
sequence: RnaAlphabet
}
/**
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "ProteinSequence".
 */
export interface ProteinSequence {
type: "protein-sequence"
identifier: Identifier
sequence: ProteinAlphabet
}
/**
 * The shape every current producer (picea, react-bio-viz, acacia) actually emits: no alphabet discriminator.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "UntypedSequence".
 */
export interface UntypedSequence {
identifier: Identifier
sequence: string
}
/**
 * A GFF3-derived sequence feature (gene model) node. Shared verbatim between picea (SequenceInterval) and react-bio-viz (SequenceInterval). seqid/start/end/strand stay flat rather than nesting under core/Location, to match the real current wire shape exactly.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "Annotation".
 */
export interface Annotation {
/**
 * Wire-format object-kind discriminator (see betula's versioning policy). Optional. Distinct from 'interval_type': 'type' says this is a betula Annotation object, 'interval_type' says which GFF3 feature kind it is.
 */
type?: "annotation"
ID: Identifier
seqid: Identifier1
/**
 * GFF3 column 2.
 */
source: string
/**
 * GFF3 column 3 (feature type), e.g. 'gene', 'mRNA', 'exon', 'CDS'.
 */
interval_type: string
/**
 * GFF3 column 4: 1-based inclusive start.
 */
start: number
/**
 * GFF3 column 5: 1-based inclusive end.
 */
end: number
/**
 * GFF3 column 6. '.' is the GFF3 convention for 'no score'.
 */
score: (number | ".")
/**
 * GFF3 column 7.
 */
strand: ("+" | "-" | ".")
/**
 * GFF3 column 8 (CDS reading-frame phase). '.' is the GFF3 convention for 'not applicable'.
 */
phase: ((0 | 1 | 2) | ".")
attributes: Metadata
/**
 * Nested features, e.g. mRNA under gene, exon/CDS under mRNA.
 */
children: Annotation[]
}
/**
 * Free-form key/value metadata, GFF3-attribute-style: each value is a single string, or a list of strings for multi-valued tags.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "Metadata".
 */
export interface Metadata {
[k: string]: string | string[]
}
/**
 * A full BLAST search result, matching blastserver's parsed-XML shape: hit-level, with nested HSPs and taxonomy/cluster enrichment. react-bio-viz's flattened single-row-per-hit visualization shape is a derived view of this, not a separate wire format. Numeric fields here are typed as numbers; blastserver's raw XML parse currently yields numeric strings and must cast before serializing against this schema.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "BlastResult".
 */
export interface BlastResult {
/**
 * Wire-format object-kind discriminator (see betula's versioning policy). Optional.
 */
type?: "blast-result"
program: string
version: string
db: string
queryId: Identifier
queryLen: number
queryTitle: string
hits: Hit[]
stat: string
message: string
taxonomyTrees?: TaxonomyNode[]
}
/**
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "Hit".
 */
export interface Hit {
accession: Identifier
title: string
taxid: number
saccver: Identifier
/**
 * Resolved taxon scientific name.
 */
name: string
/**
 * @minItems 1
 */
members: [HitMember, ...(HitMember)[]]
clusterSize: number
queryCover: number
percentIdentity: number
num: number
len: number
/**
 * @minItems 1
 */
hsps: [Hsp, ...(Hsp)[]]
/**
 * Taxonomy lineage taxids.
 */
ancestors: number[]
}
/**
 * One member of a clustered hit (e.g. in a clustered_nr database); a non-clustered hit has exactly one member.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "HitMember".
 */
export interface HitMember {
accession: Identifier
title: string
taxid: number
name: string
}
/**
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "Hsp".
 */
export interface Hsp {
num: number
bitScore: number
score: number
evalue: number
identity: number
alignLen: number
queryFrom: number
queryTo: number
hitFrom: number
hitTo: number
qseq: string
hseq: string
midline: string
}
/**
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "TaxonomyNode".
 */
export interface TaxonomyNode {
id: number
name: string
ancestors: number[]
children?: TaxonomyNode[]
depth?: number
count?: number
}
/**
 * A pairwise distance matrix, shared by react-bio-viz and acacia (via @holmrenser/nj's DistanceResult). Squareness, symmetry, and a zero diagonal are semantic constraints, not checked structurally by this schema.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "DistanceMatrix".
 */
export interface DistanceMatrix {
/**
 * Wire-format object-kind discriminator (see betula's versioning policy). Optional.
 */
type?: "distance-matrix"
/**
 * @minItems 1
 */
labels: [Identifier, ...(Identifier)[]]
matrix: number[][]
/**
 * Optional display-name lookup from label to a longer/human-readable name.
 */
labelNames?: {
[k: string]: string
}
}
/**
 * A 1-based inclusive interval on a named reference sequence (GFF3 convention). Not yet consumed by another betula schema: annotation keeps seqid/start/end/strand flat to match picea's and react-bio-viz's current wire shape rather than nesting them under this. This exists as the reusable primitive for when a genomic-interval-only shape is needed, e.g. a future schema for react-bio-viz's GenomeBrowser feature tracks.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "Location".
 */
export interface Location {
seqid: Identifier
start: number
end: number
strand: ("+" | "-" | ".")
}
/**
 * A pointer to a Sequence by identifier, without embedding the sequence itself. Not yet consumed by another betula schema (every current producer embeds full Sequence objects, e.g. in alignment); this exists as the reusable primitive for when a by-reference link is needed, e.g. a hit record pointing at a locally-known query sequence instead of repeating it.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "SequenceReference".
 */
export interface SequenceReference {
identifier: Identifier
}
/**
 * A phylogenetic (or other hierarchical) tree node, shared by picea, react-bio-viz, acacia, and iqtreeserver. The root of a tree is itself a Tree node; a whole tree and a single node use the same shape, so 'type' is optional and conventionally set only on a node transmitted as a standalone document (typically the root), not repeated on every nested child.
 * 
 * This interface was referenced by `Betula`'s JSON-Schema
 * via the `definition` "Tree".
 */
export interface Tree {
/**
 * Wire-format object-kind discriminator (see betula's versioning policy). Optional; omit on nested children.
 */
type?: "tree"
/**
 * Optional node identifier. Not every producer assigns one at parse time (acacia/iqtreeserver derive ids separately); consumers must not assume it is present.
 */
id?: (string | number)
/**
 * Raw node label: a leaf name, or an internal-node label such as a bootstrap value or support string (e.g. picea's "0.989", IQ-TREE's "95.3/88"). Kept as the original string for round-tripping; parse further only if you know the producer's convention.
 */
name: string
/**
 * Branch length leading to this node.
 */
length: number
/**
 * Child nodes. Empty array for a leaf.
 */
children: Tree[]
}

/** Every betula schema title, mapped to its TypeScript type. */
export interface BetulaTypes {
  Alignment: Alignment;
  Annotation: Annotation;
  BlastResult: BlastResult;
  DistanceMatrix: DistanceMatrix;
  DnaAlphabet: DnaAlphabet;
  DnaSequence: DnaSequence;
  Hit: Hit;
  HitMember: HitMember;
  Hsp: Hsp;
  Identifier: Identifier;
  Location: Location;
  Metadata: Metadata;
  ProteinAlphabet: ProteinAlphabet;
  ProteinSequence: ProteinSequence;
  RnaAlphabet: RnaAlphabet;
  RnaSequence: RnaSequence;
  Sequence: Sequence;
  SequenceReference: SequenceReference;
  TaxonomyNode: TaxonomyNode;
  Tree: Tree;
  UntypedSequence: UntypedSequence;
  UnwrappedAlignment: UnwrappedAlignment;
  WrappedAlignment: WrappedAlignment;
}
