#!/usr/bin/env python3
"""Turn the canonical bundle into typify input, and emit src/kinds.rs.

Only typify sees the rewritten schema; runtime validation in the crate uses
the canonical bundle, so these rewrites affect generated Rust types, never
what's considered valid. Each rewrite is chosen to be equivalent:

- {"const": "x"}  ->  {"type": "string", "enum": ["x"]}
  typify 0.8 maps a string const to an unchecked serde_json::Value, which
  breaks untagged-union variant selection (e.g. an rna-sequence whose
  letters are also valid DNA would deserialize as DnaSequence). The
  single-value enum form is enforced.
- {"type": "string", "enum": ["+", "-", "."]}  ->  x-rust-type betula::Strand
  typify can't derive distinct Rust variant names from punctuation, so this
  maps to the hand-written enum in src/lib.rs. The exact source shape is
  asserted below so a schema change can't silently desync from it.

Usage: prepare_typify_input.py <bundle.json> <typify-input.json> <kinds.rs>
"""
import json
import sys
from pathlib import Path

STRAND = {"type": "string", "enum": ["+", "-", "."]}
STRAND_RUST_TYPE = {"crate": "betula", "version": "*", "path": "betula::Strand"}


def rewrite(node):
    if isinstance(node, list):
        return [rewrite(item) for item in node]
    if not isinstance(node, dict):
        return node
    node = {key: rewrite(value) for key, value in node.items()}
    if "const" in node:
        if not isinstance(node["const"], str):
            raise ValueError(f"non-string const not handled: {node['const']!r}")
        node["enum"] = [node.pop("const")]
        node["type"] = "string"
    if {k: v for k, v in node.items() if k != "description"} == STRAND:
        return {"x-rust-type": STRAND_RUST_TYPE, **({"description": node["description"]} if "description" in node else {})}
    if node.get("enum") and len(node["enum"]) > 1 and all(isinstance(v, str) and not v.isidentifier() for v in node["enum"]):
        raise ValueError(f"unhandled punctuation enum {node['enum']!r}; typify can't name its variants")
    return node


def main() -> None:
    bundle_path, out_path, kinds_path = map(Path, sys.argv[1:4])
    bundle = json.loads(bundle_path.read_text())
    out_path.write_text(json.dumps(rewrite(bundle), indent=2) + "\n")

    kinds = ",\n    ".join(bundle["$defs"])
    kinds_path.write_text(
        "// Generated by bindings/rust/scripts/prepare_typify_input.py. Do not edit.\n\n"
        f"impl_kinds! {{\n    {kinds},\n}}\n"
    )


if __name__ == "__main__":
    main()
